
[functions.habit-analyzer]
enabled = true
verify_jwt = true
import_map = "./functions/habit-analyzer/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/habit-analyzer/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/habit-analyzer/*.html" ]

[functions.task-nudge-scheduler]
enabled = true
verify_jwt = true
import_map = "./functions/task-nudge-scheduler/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/task-nudge-scheduler/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/task-nudge-scheduler/*.html" ]
